### ISSUE TITLE
OSError: [WinError 126] Module not found when initializing FS in retriever.py

### ISSUE THREAD

**Issue by khaled-benahmed** [nkap360/rag_api#1]
**Description:**

I encountered an error when trying to run the project after cloning it from GitHub. The error occurs during the initialization of the `FS` object in `retriever.py` due to a missing DLL (`fbgemm.dll`) in the PyTorch library. Below are the details of the error and my environment setup.

**Error Traceback:**

```
Traceback (most recent call last):
  File "C:\Users\\Desktop\rag_api\rag_api\app.py", line 63, in <module>
    file_searcher = FS(config=config, llm=llm)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\\Desktop\rag_api\rag_api\utils\retriever.py", line 19, in __init__
    HuggingFaceEmbeddings(model_name=self.config["embedding"])
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\rag-api-1I6wY3cw-py3.11\Lib\site-packages\langchain_community\embeddings\huggingface.py", line 64, in __init__
    import sentence_transformers
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\rag-api-1I6wY3cw-py3.11\Lib\site-packages\sentence_transformers\__init__.py", line 3, in <module>
    from .datasets import SentencesDataset, ParallelSentencesDataset
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\rag-api-1I6wY3cw-py3.11\Lib\site-packages\sentence_transformers\datasets\__init__.py", line 1, in <module>
    from .DenoisingAutoEncoderDataset import DenoisingAutoEncoderDataset
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\rag-api-1I6wY3cw-py3.11\Lib\site-packages\sentence_transformers\datasets\DenoisingAutoEncoderDataset.py", line 1, in <module>
    from torch.utils.data import Dataset
  File "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\rag-api-1I6wY3cw-py3.11\Lib\site-packages\torch\__init__.py", line 148, in <module>
    raise err
OSError: [WinError 126] Le module spécifié est introuvable. Error loading "C:\Users\\AppData\Local\pypoetry\Cache\virtualenvs\rag-api-1I6wY3cw-py3.11\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.
```

**Environment:**

- **Operating System:** Windows
- **Python Version:** 3.11
- **Virtual Environment:** Poetry

**Steps to Reproduce:**

1. Clone the project from GitHub.
2. Install dependencies using Poetry.
3. Run the application using `python app.py`.

**Additional Information:**
- I have verified that the `fbgemm.dll` file exists in the specified directory, but the error persists.

Please let me know if you need any more information or if there are any steps I can take to help debug this issue.

**Comment by khaled-benahmed** [comment]
SOLVED : Download Dependencies_x64_Release.zip from [https://github.com/lucasg/Dependencies/releases/tag/v1.11.1 903](https://github.com/lucasg/Dependencies/releases/tag/v1.11.1) or x86 if you are 32bit, then unzip and open DependenciesGui.exe, open the fbgemm.dll in DependenciesGui.exe, then it will show which file(s) you lost, after that downloading the file(s) you lost into the same folder as fbgemm.dll, and try to run the code again.
